### ISSUE TITLE
Clover doesn't show macOS

### ISSUE THREAD

**Issue by plumps** [dmitriypavlov/T430s-macOS#3]
After installing macOS Sierra to the SSD, I mounted EFI partition via __diskutil mount /dev/disk5s1__

There I copied the whole EFI directory.
__cp -r ~/Downloads/T430s-macOS/EFI /Volumes/EFI/__ 

Unfortunately after booting I can see the grey clover boot screen but no macOS to choose from
[screenshot](http://imgur.com/a/CSqrU)

**Comment by dmitriypavlov** [comment]
Please double check the HFSPlus.efi and FSInject.efi drivers.
Second cause could be a FS corruption on macOS volume.

**Comment by plumps** [comment]
I don't know which model you have  :-) But here is a [gist](https://gist.github.com/plumps/79cd432be2925bc4bdef45294d3c8805#file-txt) (T430S, i5-3320M, HD4000, 1600x900). 

AHCI is set

FS Corruption I need to check later

**Comment by plumps** [comment]
Another question. If the EFI partition is mounted to let's say __/Volumes/EFI__.

Can you send me a listing of __/Volumes/EFI__ of yours?

**Comment by plumps** [comment]
Finally I solved it. The installation process of macOS wasn't finished, cause I thought it's okay to interrupt the installation process before rebooting takes place. 

Now it's booting and everything seems to be fine. Great job 👍
