### ISSUE TITLE
T430s hangs itself up on apple logo

### ISSUE THREAD

**Issue by ansgarle** [dmitriypavlov/T430s-macOS#4]
Hi!
I tried to install macOS Sierra 10.12.6 by following you instructions, but I am stuck at the apple logo when booting. The screenshot shows the output during boot with the "-v" option.

Do you know what the issue could be?

Thanks a lot in advance!

<img width="1011" alt="screenshot" src="https://user-images.githubusercontent.com/31183149/29495154-5488a28a-85b9-11e7-89f1-d1798b502f6c.png">

**Comment by dmitriypavlov** [comment]
Not a clue, sorry, but seems like a Clover issue. Turn the Clover's logging option on and see what's going on. Then try asking for help @ https://www.tonymacx86.com/forums
