### ISSUE TITLE
brightness controls defunct after installing Supplemental Update

### ISSUE THREAD

**Issue by plumps** [dmitriypavlov/T430s-macOS#7]
Today, I installed the first update to High Sierra, and after restarting the system, the brightness controls seem to not longer be mapped to Fn+F8 and Fn+F9, which is a pain as I don't know any workaround to set the brightness in any other way.

Do you happen to know any workaround or starting point, where to look for the issue?

**Comment by plumps** [comment]
tried to set the brightness with the equally named command and received:
`$ brightness 0.5`
`brightness: failed to set brightness of display 0x2b902840 (error -536870201)`

**Comment by dmitriypavlov** [comment]
I've had the same problem after Sierra update. On the first boot there was no brightness slider in the display panel and brightness keys were disfunctional. But after a reboot everything set up and started to work. After the first HS update I didn't see any regressions either.

Try to rebuild the kextcache and cold start.

**Comment by plumps** [comment]
Same here.
